### ISSUE TITLE
tyr::actor_t: blank exception thrown on bogus input

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#1406]
When calling `tyr::actor_t::route` with some bogus request string and without specifying `interrupt` function, I get `std::exception` thrown with `e.what()` returning just "std::exception". Would be helpful to get some meaningful text that can be conveyed to the user.

**Comment by rinigus** [comment]
Example string: "{{}}"

Backtrace:

```
#0  0x00007ffff04a33ef in raise () from /lib64/libc.so.6
#1  0x00007ffff04a4fbd in abort () from /lib64/libc.so.6
#2  0x00007ffff37224d5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#3  0x00007ffff371ff56 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#4  0x00007ffff371ffb1 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#5  0x00007ffff372023c in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#6  0x00005555556f9f96 in (anonymous namespace)::from_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::exception const&) [clone .isra.246]
    ()
#7  0x00005555556fa309 in valhalla::valhalla_request_t::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, valhalla::odin::DirectionsOptions_Action) ()
#8  0x00005555556f50b9 in valhalla::tyr::actor_t::route(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&) ()
#9  0x00005555556bd883 in ValhallaMaster::route (this=0x5555563de720, json=..., result=...) at ../osmscout-server/src/valhallamaster.cpp:153
#10 0x0000555555608bff in main (argc=1, argv=0x7fffffffd7b8) at ../osmscout-server/src/main.cpp:478
```
