### ISSUE TITLE
crash in valhalla_build_transit

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#1459]
I am trying to get transit tiles and its ends always with the crash. This is with the current master (today) or 2.6.x versions.

Command: `valhalla_build_transit valhalla.json http://transit.land 1000 transit 59.29,59.58,24.44,25.09`

[would probably get the same result without BBOX, as far as I remember]

Output when running in gdb:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
2018/08/02 12:28:40.266938 [INFO] Fetching transit feeds
2018/08/02 12:28:42.226859 [INFO] 2/000/519/120.gph should have 65 stations 
2018/08/02 12:45:41.576243 [INFO] 2/000/599/760.gph should have 1 stations 
2018/08/02 12:51:11.148242 [INFO] 2/000/622/961.gph should have 2 stations 
2018/08/02 12:57:03.589324 [INFO] 2/000/643/112.gph should have 2 stations 
2018/08/02 12:57:03.763378 [INFO] 2/000/643/113.gph should have 2 stations 
...
2018/08/02 14:02:05.997299 [INFO] 2/000/895/061.gph should have 67 stations 
2018/08/02 14:02:06.181777 [INFO] 2/000/895/062.gph should have 74 stations 
2018/08/02 14:02:06.363775 [INFO] 2/000/895/063.gph should have 23 stations 
2018/08/02 14:02:35.564280 [INFO] 2/000/902/271.gph should have 2 stations 
2018/08/02 14:02:36.666442 [INFO] Finished with 3187 transit tiles in 9 feeds
2018/08/02 14:02:36.672975 [INFO] Fetching 3187 transit tiles with 4 threads...
[New Thread 0x7ffff0235700 (LWP 18884)]
[New Thread 0x7fffefa34700 (LWP 18885)]
2018/08/02 14:02:36.673577 [INFO] Fetching transit/2/000/750/945.pbf
2018/08/02 14:02:36.673776 [INFO] Fetching transit/2/000/811/457.pbf
[New Thread 0x7fffef233700 (LWP 18886)]
[New Thread 0x7fffeea32700 (LWP 18887)]
2018/08/02 14:02:36.674345 [INFO] Fetching transit/2/000/703/579.pbf
2018/08/02 14:02:36.675700 [INFO] Fetching transit/2/000/778/350.pbf
*** longjmp causes uninitialized stack frame ***: /data/valhalla/install/bin/valhalla_build_transit terminated

Thread 1 "valhalla_build_" received signal SIGABRT, Aborted.
0x00007ffff48dbfa0 in raise () from /lib64/libc.so.6
```

Backtrace of one of the worker threads:

```
Thread 5 (Thread 0x7fffeea32700 (LWP 18887)):
#0  0x00007ffff499b9e4 in poll () from /lib64/libc.so.6
#1  0x00007ffff691e839 in ?? () from /usr/lib64/libcurl.so.4
#2  0x00007ffff69189f1 in curl_multi_wait () from /usr/lib64/libcurl.so.4
#3  0x00007ffff691351f in curl_easy_perform () from /usr/lib64/libcurl.so.4
#4  0x00005555555a7274 in pt_curler_t::operator() (this=0x7fffeea31bf0, 
    url="http://transit.land/api/v1/route_stop_patterns?total=false&per_page=100&traversed_by=r-u0jdd-4541", retry_if_no="route_stop_patterns", gzip=true)
    at /data/valhalla/valhalla/src/mjolnir/valhalla_build_transit.cc:153
#5  0x000055555558e78a in fetch_tiles (pt=..., queue=std::priority_queue wrapping: std::vector of length 3183, capacity 4096 = {...}, uniques=..., promise=...)
    at /data/valhalla/valhalla/src/mjolnir/valhalla_build_transit.cc:932
#6  0x00005555555bb966 in std::__invoke_impl<void, void (*)(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&), boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&> (
    __f=@0x555555d26538: 0x55555558c8ff <fetch_tiles(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&)>, __args#0=..., 
    __args#1=std::priority_queue wrapping: std::vector of length 3183, capacity 4096 = {...}, __args#2=..., __args#3=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/invoke.h:60
#7  0x00005555555af1c1 in std::__invoke<void (*)(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&), boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&> (
    __fn=@0x555555d26538: 0x55555558c8ff <fetch_tiles(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&)>, __args#0=..., 
    __args#1=std::priority_queue wrapping: std::vector of length 3183, capacity 4096 = {...}, __args#2=..., __args#3=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/invoke.h:95
#8  0x00005555556056a3 in std::thread::_Invoker<std::tuple<void (*)(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&), boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x555555d26518) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:234
#9  0x000055555560454c in std::thread::_Invoker<std::tuple<void (*)(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&), boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&> >::operator() (
    this=0x555555d26518) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:243
#10 0x0000555555602ab0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&), boost::property_tree::basic_ptree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::priority_queue<weighted_tile_t, std::vector<weighted_tile_t, std::allocator<weighted_tile_t> >, std::less<weighted_tile_t> >&, unique_transit_t&, std::promise<std::__cxx11::list<valhalla::baldr::GraphId, std::allocator<valhalla::baldr::GraphId> > >&> > >::_M_run (this=0x555555d26510) at /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/thread:186
#11 0x00007ffff54c2f0e in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#12 0x00007ffff4c6f90a in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff49a733f in clone () from /lib64/libc.so.6
```

Main thread:

```
Thread 1 (Thread 0x7ffff7f92740 (LWP 8365)):
#0  0x00007ffff48dbfa0 in raise () from /lib64/libc.so.6
#1  0x00007ffff48ddb7d in abort () from /lib64/libc.so.6
#2  0x00007ffff49222bf in ?? () from /lib64/libc.so.6
#3  0x00007ffff49baecc in ?? () from /lib64/libc.so.6
#4  0x00007ffff49baef1 in __fortify_fail () from /lib64/libc.so.6
#5  0x00007ffff49bad0d in ?? () from /lib64/libc.so.6
#6  0x00007ffff49bac6b in __longjmp_chk () from /lib64/libc.so.6
#7  0x00007ffff68f5075 in ?? () from /usr/lib64/libcurl.so.4
#8  <signal handler called>
#9  0x00007ffff4c70c3d in pthread_join () from /lib64/libpthread.so.0
#10 0x00007ffff54c31d3 in std::thread::join() () from /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
#11 0x00005555555901a8 in fetch (pt=..., tiles=std::priority_queue wrapping: std::vector of length 3183, capacity 4096 = {...}, thread_count=4)
    at /data/valhalla/valhalla/src/mjolnir/valhalla_build_transit.cc:1003
#12 0x000055555559c183 in main (argc=6, argv=0x7fffffffd638) at /data/valhalla/valhalla/src/mjolnir/valhalla_build_transit.cc:2431
```

OS: Gentoo 
Compiler: gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0

Result of running - nothing is written in transit folder

**Comment by rinigus** [comment]
Looks like its Gentoo bug. On Ubuntu, all worked as expected. Closing
