### ISSUE TITLE
Double free on second call to valhalla::thor::CostMatrix::SourceToTarget()

### ISSUE THREAD

**Issue by maestroIgor** [valhalla/valhalla#1531]
I have built Valhalla with enabled sanitazers and have got this error.   
```
==21069==ERROR: AddressSanitizer: attempting double-free on 0x7ff4f9219800 in thread T6:
    #0 0x7ff56c5b6490 in operator delete[](void*) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe1490)
    #1 0x55cc426757cc in valhalla::thor::EdgeStatus::clear() /home/ig/SOURSES_D/deps-c/valhalla/valhalla/thor/edgestatus.h:64
    #2 0x55cc4267560b in valhalla::thor::EdgeStatus::~EdgeStatus() /home/ig/SOURSES_D/deps-c/valhalla/valhalla/thor/edgestatus.h:55
    #3 0x55cc4267a103 in void std::_Destroy<valhalla::thor::EdgeStatus>(valhalla::thor::EdgeStatus*) /usr/include/c++/7/bits/stl_construct.h:98
    #4 0x55cc426799be in void std::_Destroy_aux<false>::__destroy<valhalla::thor::EdgeStatus*>(valhalla::thor::EdgeStatus*, valhalla::thor::EdgeStatus*) /usr/include/c++/7/bits/stl_construct.h:108
    #5 0x55cc42678ff5 in void std::_Destroy<valhalla::thor::EdgeStatus*>(valhalla::thor::EdgeStatus*, valhalla::thor::EdgeStatus*) /usr/include/c++/7/bits/stl_construct.h:137
    #6 0x55cc426784a8 in void std::_Destroy<valhalla::thor::EdgeStatus*, valhalla::thor::EdgeStatus>(valhalla::thor::EdgeStatus*, valhalla::thor::EdgeStatus*, std::allocator<valhalla::thor::EdgeStatus>&) /usr/include/c++/7/bits/stl_construct.h:206
    #7 0x55cc42ab3be3 in std::vector<valhalla::thor::EdgeStatus, std::allocator<valhalla::thor::EdgeStatus> >::_M_erase_at_end(valhalla::thor::EdgeStatus*) /usr/include/c++/7/bits/stl_vector.h:1513
    #8 0x55cc42ab09be in std::vector<valhalla::thor::EdgeStatus, std::allocator<valhalla::thor::EdgeStatus> >::clear() /usr/include/c++/7/bits/stl_vector.h:1248
    #9 0x55cc42a9e1ee in valhalla::thor::CostMatrix::Clear() /home/ig/SOURSES_D/deps-c/valhalla/src/thor/costmatrix.cc:77
    #10 0x55cc42a9ee0b in valhalla::thor::CostMatrix::SourceToTarget(google::protobuf::RepeatedPtrField<valhalla::odin::Location> const&, google::protobuf::RepeatedPtrField<valhalla::odin::Location> const&, valhalla::baldr::GraphReader&, std::shared_ptr<valhalla::sif::DynamicCost> const*, valhalla::sif::TravelMode, float) /home/ig/SOURSES_D/deps-c/valhalla/src/thor/costmatrix.cc:120
```
It is caused by typos in method `void CostMatrix::Clear()`:
```cpp
  for (auto es : target_edgestatus_) {
    es.clear();
  }
  target_edgestatus_.clear();
```
Object `EdgeStatus` is copied instead of addressing by reference.

**Comment by maestroIgor** [comment]
Fixed.
