### ISSUE TITLE
Seg fault in pbfadminbuilder

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#353]
(2015-11-21T13:08:34Z) @molind : originally created valhalla/mjolnir#319

I built trunk valhalla libraries with gcc-5.2.1 (default gcc version on ubuntu 15.10)

Tried to build routing info for belarus-latest extract, but it segraults somewhere in geos. There is backtrace:

```
Starting program: /usr/local/bin/pbfadminbuilder -c conf/valhalla.json belarus-latest.osm.pbf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2015/11/21 11:04:53.490784 [INFO] Parsing files: belarus-latest.osm.pbf
2015/11/21 11:04:53.490864 [INFO] Parsing relations...
2015/11/21 11:04:56.642286 [INFO] Finished with 27 admin polygons comprised of 7377 ways
2015/11/21 11:04:56.642316 [INFO] Parsing ways...
2015/11/21 11:05:00.218489 [INFO] Finished with 537 ways comprised of 45616 nodes
2015/11/21 11:05:00.218518 [INFO] Parsing nodes...
2015/11/21 11:05:03.398816 [INFO] Finished with 45074 nodes
2015/11/21 11:05:03.455378 [INFO] SpatiaLite loaded as an extension
2015/11/21 11:20:49.353703 [INFO] Created admin table.
2015/11/21 11:20:50.627007 [INFO] Inserted 8 admin areas
2015/11/21 11:20:51.970701 [INFO] Created spatial index
2015/11/21 11:20:52.072800 [INFO] Created Level index
2015/11/21 11:20:52.164704 [INFO] Created Drive On Right index
2015/11/21 11:20:52.164949 [INFO] Done updating drive on right column.
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ad953e in geos::geom::CoordinateArraySequence::setOrdinate(unsigned long, unsigned long, double) () from /usr/lib/x86_64-linux-gnu/libgeos-3.5.0.so
(gdb) bt
#0  0x00007ffff7ad953e in geos::geom::CoordinateArraySequence::setOrdinate(unsigned long, unsigned long, double) ()
   from /usr/lib/x86_64-linux-gnu/libgeos-3.5.0.so
#1  0x00007ffff35186f6 in GEOSCoordSeq_setOrdinate_r (extHandle=0xde0bb0, cs=<optimized out>, idx=<optimized out>, dim=<optimized out>, 
    val=23.178339004516602) at geos_ts_c.cpp:3487
#2  0x00007ffff5f944a5 in ?? () from /usr/lib/x86_64-linux-gnu/libspatialite.so.7
#3  0x00007ffff5f9df1a in gaiaGeomCollCovers () from /usr/lib/x86_64-linux-gnu/libspatialite.so.7
#4  0x00007ffff6008d4b in ?? () from /usr/lib/x86_64-linux-gnu/libspatialite.so.7
#5  0x00007ffff67666ef in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#6  0x00007ffff676f827 in sqlite3_step () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#7  0x00007ffff677089a in sqlite3_exec () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#8  0x0000000000434558 in BuildAdminFromPBF (pt=..., input_files=std::vector of length 1, capacity 1 = {...}) at src/mjolnir/pbfadminbuilder.cc:491
 0x000000000042fbab in main (argc=<optimized out>, argv=<optimized out>) at src/mjolnir/pbfadminbuilder.cc:522
(gdb) 
```

(2015-11-24T18:00:09Z) @gknisely : We have currently tested with gcc4.9 and ubuntu 14.04.  We may have to put
in some version logic to fix this.  We will look at this as soon as we can.

--Greg.

**Comment by dnesbitt61** [comment]
Closing this issue due to lack of recent activity. Feel free to open a new issue if this is still important.
