### ISSUE TITLE
valhalla_build_tiles coredumps when creating data

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#418]
(2016-07-18T11:25:22Z) @bentley : originally created valhalla/mjolnir#502

I tried to go through the steps in the [Getting Started guide](https://github.com/valhalla/mjolnir/blob/master/docs/getting_started_guide.md) using mjolnir-1.0.9 and an OpenBSD 6.0 snapshot.
1. Created the directory `/data` with appropriate permissions
2. Used the [config file from valhalla/conf](https://github.com/valhalla/conf/blob/ae9780d94f2eb890d9f6f5b705950e55ef92c727/valhalla.json), unmodified
3. Downloaded `albuquerque_new-mexico.osm.pbf` from Mapzen
4. Ran `valhalla_build_tiles --config valhalla.json albuquerque_new-mexico.osm.pbf`

The results:

```
2016/07/18 11:21:08.521323 [INFO] Parsing files: /tmp/albuquerque_new-mexico.osm.pbf
2016/07/18 11:21:08.521565 [INFO] Parsing ways...
2016/07/18 11:21:11.592452 [INFO] Finished with 31404 routable ways containing 217742 nodes
2016/07/18 11:21:11.592504 [INFO] Parsing relations...
2016/07/18 11:21:11.813583 [INFO] Finished with 135 simple restrictions
2016/07/18 11:21:11.813599 [INFO] Sorting osm way node references by node id...
2016/07/18 11:21:12.015028 [INFO] Sorting osm access tags by way id...
2016/07/18 11:21:12.016430 [INFO] Finished
2016/07/18 11:21:12.016439 [INFO] Parsing nodes...
2016/07/18 11:21:13.808302 [INFO] Finished with 166143 nodes contained in routable ways
2016/07/18 11:21:13.809397 [INFO] Sorting osm way node references by way index and node shape index...
2016/07/18 11:21:14.033524 [INFO] Finished
2016/07/18 11:21:14.345494 [INFO] Creating graph edges from ways...
2016/07/18 11:21:15.384977 [INFO] Finished with 76137 graph edges
2016/07/18 11:21:15.389582 [INFO] Sorting graph...
2016/07/18 11:21:15.453275 [INFO] Finished with 3579 graph nodes
2016/07/18 11:21:15.483896 [INFO] Reclassifying link graph edges...
2016/07/18 11:21:15.774470 [INFO] Finished with 2 reclassified.
2016/07/18 11:21:15.776744 [INFO] Reclassifying ferry connection graph edges...
2016/07/18 11:21:15.826601 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 0, 0 edges reclassified.
Abort trap (core dumped) 
```

Backtrace from the coredump:

```
(gdb) bt
#0  0x00000a13e8bdb3ba in thrkill () at <stdin>:2
#1  0x00000a13e8bf68c9 in *_libc_abort ()
    at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x00000a13781392c5 in _Unwind_Resume (exc=0xa136fd1c650)
    at /usr/src/gnu/usr.bin/cc/libgcc/../../../gcc/gcc/unwind.inc:238
#3  0x00000a1350995c23 in boost::filesystem::recursive_directory_iterator::recursive_directory_iterator(boost::filesystem::path const&, boost::filesystem::symlink_option::enum_type) () from /usr/local/lib/libvalhalla_mjolnir.so.0.0
#4  0x00000a1310493385 in (anonymous namespace)::get_files (root_dir=...)
    at src/skadi/sample.cc:31
#5  valhalla::skadi::sample::sample (this=0xa13229f4100, data_source=...)
    at src/skadi/sample.cc:82
#6  0x00000a135090f9ca in valhalla::mjolnir::GraphBuilder::Build (pt=..., 
    osmdata=..., ways_file=..., way_nodes_file=...)
    at src/mjolnir/graphbuilder.cc:838
#7  0x00000a11101389c7 in main (argc=<optimized out>, argv=<optimized out>)
    at src/mjolnir/valhalla_build_tiles.cc:132
```

What am I missing?

(2016-07-18T12:17:17Z) @dnesbitt61 : Are you trying to merge in elevation data? From this it looks like it is trying to access elevation data (skadi) and is having issues. If you do not have elevation data maybe there is an issue with skadi on OpenBSD? Maybe create an empty /data/valhalla/elevation directory as a test.

(2016-07-19T07:02:19Z) @bentley : That’s it; valhalla/conf’s default `valhalla.json` looks for elevation data but I hadn’t fetched any.

So I used skadi’s valhalla_build_elevation to create `/data/valhalla/elevation/N35/N35W107.hgt`(this should include all of Albuquerque, which is at 35°06′39″N 106°36′36″W). I also ran valhalla_build_timezones and valhalla_build_admins (against the Albuquerque PBF, not a planet), because those databases were mentioned in the default config.

This time, valhalla_build_tiles makes it farther, but segfaults again:

```
$ valhalla_build_tiles -c valhalla.json albuquerque_new-mexico.osm.pbf
2016/07/19 06:50:41.706677 [INFO] Parsing files: /tmp/y/albuquerque_new-mexico.osm.pbf
2016/07/19 06:50:41.706752 [INFO] Parsing ways...
2016/07/19 06:50:44.658379 [INFO] Finished with 31404 routable ways containing 217742 nodes
2016/07/19 06:50:44.658405 [INFO] Parsing relations...
2016/07/19 06:50:44.878949 [INFO] Finished with 135 simple restrictions
2016/07/19 06:50:44.878984 [INFO] Sorting osm way node references by node id...
2016/07/19 06:50:45.075748 [INFO] Sorting osm access tags by way id...
2016/07/19 06:50:45.076984 [INFO] Finished
2016/07/19 06:50:45.077004 [INFO] Parsing nodes...
2016/07/19 06:50:46.863377 [INFO] Finished with 166143 nodes contained in routable ways
2016/07/19 06:50:46.864231 [INFO] Sorting osm way node references by way index and node shape index...
2016/07/19 06:50:47.090495 [INFO] Finished
2016/07/19 06:50:47.428041 [INFO] Creating graph edges from ways...
2016/07/19 06:50:48.457319 [INFO] Finished with 76137 graph edges
2016/07/19 06:50:48.462524 [INFO] Sorting graph...
2016/07/19 06:50:48.526221 [INFO] Finished with 3579 graph nodes
2016/07/19 06:50:48.557535 [INFO] Reclassifying link graph edges...
2016/07/19 06:50:48.838637 [INFO] Finished with 2 reclassified.
2016/07/19 06:50:48.840763 [INFO] Reclassifying ferry connection graph edges...
2016/07/19 06:50:48.890915 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 0, 0 edges reclassified.
2016/07/19 06:50:48.905711 [INFO] Building 7 tiles with 4 threads...
2016/07/19 06:50:49.324946 [WARN] Local Edge Index exceeds max: 128
2016/07/19 06:50:49.325998 [WARN] Local Edge Index exceeds max: 129
2016/07/19 06:50:49.327749 [WARN] Local Edge Index exceeds max: 130
…(continues for another 1700 lines)
2016/07/19 06:50:50.199086 [WARN] Local Edge Index exceeds max: 846
2016/07/19 06:50:50.199099 [WARN] Local Edge Index exceeds max: 847
2016/07/19 06:50:50.199118 [WARN] Local Edge Index exceeds max: 848
2016/07/19 06:50:50.199127 [ERROR] NodeInfo: edge count exceeds max: 849
Segmentation fault
```

Backtrace from the coredump:

```
(gdb) bt
#0  (anonymous namespace)::BuildTileSet (ways_file=..., way_nodes_file=..., nodes_file=..., edges_file=..., hierarchy=..., osmdata=..., sample=..., tile_start=..., tile_end=..., 
    tile_creation_date=930, pt=..., result=...) at src/mjolnir/graphbuilder.cc:701
#1  0x00001c08e2ed43f7 in std::_Bind_simple<void (*(std::reference_wrapper<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::reference_wrapper<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::reference_wrapper<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::reference_wrapper<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::reference_wrapper<const valhalla::baldr::TileHierarchy>, std::reference_wrapper<const valhalla::mjolnir::OSMData>, std::reference_wrapper<const std::unique_ptr<const valhalla::skadi::sample, std::default_delete<const valhalla::skadi::sample> > >, std::_Rb_tree_const_iterator<std::pair<const valhalla::baldr::GraphId, long unsigned int> >, std::_Rb_tree_const_iterator<std::pair<const valhalla::baldr::GraphId, long unsigned int> >, unsigned int, std::reference_wrapper<const boost::property_tree::basic_ptree<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::reference_wrapper<std::promise<valhalla::mjolnir::DataQuality> >))(const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const valhalla::baldr::TileHierarchy&, const valhalla::mjolnir::OSMData&, const std::unique_ptr<const valhalla::skadi::sample, std::default_delete<const valhalla::skadi::sample> >&, std::_Rb_tree_const_iterator<std::pair<const valhalla::baldr::GraphId, long unsigned int> >, std::_Rb_tree_const_iterator<std::pair<const valhalla::baldr::GraphId, long unsigned int> >, unsigned int, const boost::property_tree::basic_ptree<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::promise<valhalla::mjolnir::DataQuality>&)>::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul, 9ul, 10ul, 11ul> (this=<optimized out>) at /usr/local/include/c++/4.9.3/functional:1700
#2  std::_Bind_simple<void (*(std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<valhalla::baldr::TileHierarchy const>, std::reference_wrapper<valhalla::mjolnir::OSMData const>, std::reference_wrapper<std::unique_ptr<valhalla::skadi::sample const, std::default_delete<valhalla::skadi::sample const> > const>, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, unsigned int, std::reference_wrapper<boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const>, std::reference_wrapper<std::promise<valhalla::mjolnir::DataQuality> >))(std::string const&, std::string const&, std::string const&, std::string const&, valhalla::baldr::TileHierarchy const&, valhalla::mjolnir::OSMData const&, std::unique_ptr<valhalla::skadi::sample const, std::default_delete<valhalla::skadi::sample const> > const&, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, unsigned int, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&, std::promise<valhalla::mjolnir::DataQuality>&)>::operator()() (
    this=<optimized out>) at /usr/local/include/c++/4.9.3/functional:1688
#3  std::thread::_Impl<std::_Bind_simple<void (*(std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<std::string const>, std::reference_wrapper<valhalla::baldr::TileHierarchy const>, std::reference_wrapper<valhalla::mjolnir::OSMData const>, std::reference_wrapper<std::unique_ptr<valhalla::skadi::sample const, std::default_delete<valhalla::skadi::sample const> > const>, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, unsigned int, std::reference_wrapper<boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const>, std::reference_wrapper<std::promise<valhalla::mjolnir::DataQuality> >))(std::string const&, std::string const&, std::string const&, std::string const&, valhalla::baldr::TileHierarchy const&, valhalla::mjolnir::OSMData const&, std::unique_ptr<valhalla::skadi::sample const, std::default_delete<valhalla::skadi::sample const> > const&, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, std::_Rb_tree_const_iterator<std::pair<valhalla::baldr::GraphId const, unsigned long> >, unsigned int, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&, std::promise<valhalla::mjolnir::DataQuality>&)> >::_M_run() (this=<optimized out>) at /usr/local/include/c++/4.9.3/thread:115
#4  0x00001c08f8e6b100 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/libstdc++-v3/src/c++11/thread.cc:84
#5  0x00001c08ad79c9de in _rthread_start (v=0x351) at /usr/src/lib/librthread/rthread.c:115
#6  0x00001c08fa6fa2db in __tfork_thread () at /usr/src/lib/libc/arch/amd64/sys/tfork_thread.S:75
#7  0x0000000000000000 in ?? ()
```

(2016-07-25T15:20:00Z) @dnesbitt61 : Something is quite wrong - should definitely not be seeing edge counts exceeding the maximum. 
I can run on Ubuntu without elevation tiles:

2016/07/25 15:18:11.952842 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 0, 0 edges reclassified.
2016/07/25 15:18:11.953521 [WARN] /data/valhalla/elevation/ has no elevation tiles

I do not see the edge exceed max issues. 

(2016-07-25T15:33:53Z) @kevinkreiser : I'm not sure of the result of `valhalla_build_admins` on extracts. What happens if you build without the admin database?

**Comment by dnesbitt61** [comment]
Closing this issue due to lack of new information/activity. Feel free to open a new issue.
