### ISSUE TITLE
Question: Unable to recreate route results

### ISSUE THREAD

**Issue by thomthom** [valhalla/valhalla#4729]
I'm currently experimenting with Valhalla. Part of that I am trying to route along the Swedish TET route:
https://transeurotrail.org/sweden/#3.22/62.40/18.00

I'm using that GPX only as a visual reference to plot my own route points:
![bilde](https://github.com/valhalla/valhalla/assets/192418/24899559-2b03-4d93-b62e-e9fb111d6254)
(Red route: the TET reference, blue route: the calculated route returned from Valhalla's `route`)

Now, whenever I try to make it route along that red TET route I keep getting `RuntimeError: No path could be found for input`

I went to `valhalla.openstreetmap.de` to try to reproduce there:
https://valhalla.openstreetmap.de/directions?profile=motorcycle&wps=15.433902740478517%2C62.73511203446039%2C15.354852676391603%2C62.68182547122809%2C15.098090171813967%2C62.62366757547452%2C15.051784515380861%2C62.588599477333204%2C14.918575286865236%2C62.465891689287695%2C14.926772117614748%2C62.40973496722765%2C14.960503578186037%2C62.363368042496205%2C15.001659393310549%2C62.29530918402997%2C15.000972747802736%2C62.243329370717014%2C14.929175376892092%2C62.19432284479635%2C14.881153106689455%2C62.14260985737117%2C14.832530021667482%2C62.134888407387116%2C14.815557003021242%2C62.14736208283421%2C14.782437086105348%2C62.146394654360215%2C14.65451717376709%2C62.08961318096257%2C14.638831615448%2C62.040045187073545%2C14.543827772140505%2C62.04327947312061%2C14.444854259490969%2C62.014339756040584%2C14.464616775512697%2C61.99614966586813

In that case it works:
![bilde](https://github.com/valhalla/valhalla/assets/192418/4845ced1-99da-44ba-86f3-2cddfe64818f)

I grabbed the data from the response and tried to use that to replicate in my own `pyvalhalla` app:

```json
{
  "costing": "motorcycle",
  "costing_options": {
    "motorcycle": {
      "exclude_polygons": [],
      "maneuver_penalty": 5,
      "country_crossing_penalty": 0,
      "country_crossing_cost": 600,
      "width": 1.6,
      "height": 1.9,
      "use_highways": 0.2,
      "use_tolls": 1,
      "use_ferry": 1,
      "ferry_cost": 300,
      "use_living_streets": 0.5,
      "use_tracks": 0.8,
      "private_access_penalty": 450,
      "ignore_closures": false,
      "ignore_restrictions": false,
      "ignore_access": false,
      "closure_factor": 9,
      "service_penalty": 15,
      "service_factor": 1,
      "exclude_unpaved": 0,
      "shortest": false,
      "exclude_cash_only_tolls": false,
      "top_speed": 140,
      "fixed_speed": 0,
      "toll_booth_penalty": 0,
      "toll_booth_cost": 15,
      "gate_penalty": 300,
      "gate_cost": 30,
      "include_hov2": false,
      "include_hov3": false,
      "include_hot": false,
      "disable_hierarchy_pruning": false,
      "use_trails": 1
    }
  },
  "exclude_polygons": [],
  "locations": [
    {
      "lon": 15.433902740478517,
      "lat": 62.73511203446039,
      "type": "break"
    },
    {
      "lon": 15.354852676391603,
      "lat": 62.68182547122809,
      "type": "via"
    },
    {
      "lon": 15.098090171813967,
      "lat": 62.62366757547452,
      "type": "via"
    },
    {
      "lon": 15.051784515380861,
      "lat": 62.588599477333204,
      "type": "via"
    },
    {
      "lon": 14.918575286865236,
      "lat": 62.465891689287695,
      "type": "via"
    },
    {
      "lon": 14.926772117614748,
      "lat": 62.40973496722765,
      "type": "via"
    },
    {
      "lon": 14.960503578186037,
      "lat": 62.363368042496205,
      "type": "via"
    },
    {
      "lon": 15.001659393310549,
      "lat": 62.29530918402997,
      "type": "via"
    },
    {
      "lon": 15.000972747802736,
      "lat": 62.243329370717014,
      "type": "via"
    },
    {
      "lon": 14.929175376892092,
      "lat": 62.19432284479635,
      "type": "via"
    },
    {
      "lon": 14.881153106689455,
      "lat": 62.14260985737117,
      "type": "via"
    },
    {
      "lon": 14.832530021667482,
      "lat": 62.134888407387116,
      "type": "via"
    },
    {
      "lon": 14.815557003021242,
      "lat": 62.14736208283421,
      "type": "via"
    },
    {
      "lon": 14.782437086105348,
      "lat": 62.146394654360215,
      "type": "via"
    },
    {
      "lon": 14.65451717376709,
      "lat": 62.08961318096257,
      "type": "via"
    },
    {
      "lon": 14.638831615448,
      "lat": 62.040045187073545,
      "type": "via"
    },
    {
      "lon": 14.543827772140505,
      "lat": 62.04327947312061,
      "type": "via"
    },
    {
      "lon": 14.444854259490969,
      "lat": 62.014339756040584,
      "type": "via"
    },
    {
      "lon": 14.464616775512697,
      "lat": 61.99614966586813,
      "type": "break"
    }
  ],
  "directions_options": {
    "units": "kilometers"
  },
  "id": "valhalla_directions"
}
```

But I still get `RuntimeError: No path could be found for input`

The tile set I'm using is an extract of Norway, Sweden, Denmark and Finland - taken from the Europe tileset.
![2024-05-10_16h13_47](https://github.com/valhalla/valhalla/assets/192418/ffac59ae-75c3-4875-9495-9558b1f2f25d)

I'm able to route around in that region fine on larger roads:
![2024-05-10_19h08_01](https://github.com/valhalla/valhalla/assets/192418/4bae4dc3-f6d7-4078-972a-b22f28123407)

So I was thinking my data set was good. But for some reason I cannot replicate the routing along the TET route, which goes on smaller dirt roads. My assumption was that with the same input query I should get the same output. And I was assuming that given my own data set was covering the same region (and well beyond) this should work.

Any ideas to what is producing this difference result?

I made a minimal repro python app:

```py
import json
from valhalla import Actor, get_config

tiles_tar = './graphs/nordics/custom_files/valhalla_tiles.tar'
config = get_config(tile_extract=tiles_tar, verbose=True)
config['service_limits']['auto']['max_distance'] = 2_000_000
config['service_limits']['motorcycle']['max_distance'] = 2_000_000

with open('research/valhalla-app/sweden-tet-routing-request.json', 'r') as file:
    params = json.load(file)

actor = Actor(config)
route = actor.route(params)

print(route)
```

Output:
```
2024/05/13 12:34:20.789315 [INFO] Tile extract successfully loaded with tile count: 6423
2024/05/13 12:34:20.789496 [WARN] (stat): /data/valhalla/traffic.tar No such file or directory
2024/05/13 12:34:20.789563 [WARN] Traffic tile extract could not be loaded
2024/05/13 12:34:20.809913 [INFO] algorithm::bidirectional_a*
2024/05/13 12:34:20.833453 [ERROR] Reverse search exhausted: n = 3,1825
2024/05/13 12:34:20.846238 [ERROR] Reverse search exhausted: n = 4,10013
Traceback (most recent call last):
  File "C:\Users\user\source\valhalla\test.py", line 13, in <module>
    route = actor.route(params)
            ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\source\valhalla\.venv\Lib\site-packages\valhalla\actor.py", line 18, in wrapped
    return json.loads(func(args[0], json.dumps(args[1])))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\source\valhalla\.venv\Lib\site-packages\valhalla\actor.py", line 80, in route
    return super().route(req)
           ^^^^^^^^^^^^^^^^^^
RuntimeError: No path could be found for input
```

**Comment by kevinkreiser** [comment]
interesting, that looks like a bug to me! the way its supposed to work is that this exception is caught on the c++ side and then wrapped by an error json. what seems to be happening is that its not being caught anymore and bubbling all the way up to python. if we can reproduce we can certainly track it down and fix it so that it does the error handling properly. 

now to the larger issue about reproducability on your data versus the server. you are right to expect the same results given the same request. if you had exactly the same data then you certainly should get the same results so likely there is some difference in the data. checking the timestamp on the data shows that it is up to date so now i am wondering where the failure could be. on your side we can narrow it down by removing locations until the route succeeds. that will tell us on which leg of the route the failure occurs. would you be able to give that a shot? narrowing it down to where its failing a bit

**Comment by thomthom** [comment]
> interesting, that looks like a bug to me! the way its supposed to work is that this exception is caught on the c++ side and then wrapped by an error json. what seems to be happening is that its not being caught anymore and bubbling all the way up to python. if we can reproduce we can certainly track it down and fix it so that it does the error handling properly.

Right, I was wondering why the error was a generic `RuntimeError` and not something more domain specific.

---

> now to the larger issue about reproducability on your data versus the server. you are right to expect the same results given the same request. if you had exactly the same data then you certainly should get the same results so likely there is some difference in the data. checking the timestamp on the data shows that it is up to date so now i am wondering where the failure could be. on your side we can narrow it down by removing locations until the route succeeds. that will tell us on which leg of the route the failure occurs. would you be able to give that a shot? narrowing it down to where its failing a bit

Simplest passing is to remove all `via` points:

```json
{
  "costing": "motorcycle",
  "costing_options": {
    "motorcycle": {
      "exclude_polygons": [],
      "maneuver_penalty": 5,
      "country_crossing_penalty": 0,
      "country_crossing_cost": 600,
      "width": 1.6,
      "height": 1.9,
      "use_highways": 0.2,
      "use_tolls": 1,
      "use_ferry": 1,
      "ferry_cost": 300,
      "use_living_streets": 0.5,
      "use_tracks": 0.8,
      "private_access_penalty": 450,
      "ignore_closures": false,
      "ignore_restrictions": false,
      "ignore_access": false,
      "closure_factor": 9,
      "service_penalty": 15,
      "service_factor": 1,
      "exclude_unpaved": 0,
      "shortest": false,
      "exclude_cash_only_tolls": false,
      "top_speed": 140,
      "fixed_speed": 0,
      "toll_booth_penalty": 0,
      "toll_booth_cost": 15,
      "gate_penalty": 300,
      "gate_cost": 30,
      "include_hov2": false,
      "include_hov3": false,
      "include_hot": false,
      "disable_hierarchy_pruning": false,
      "use_trails": 1
    }
  },
  "exclude_polygons": [],
  "locations": [
    {
      "lon": 15.433902740478517,
      "lat": 62.73511203446039,
      "type": "break"
    },
    {
      "lon": 14.464616775512697,
      "lat": 61.99614966586813,
      "type": "break"
    }
  ],
  "directions_options": {
    "units": "kilometers"
  },
  "id": "valhalla_directions"
}
```

I then started to reintroduce them one by one. (I had expected to see it fail on the first via point, but that was not the case)

The second one (that relate to #3 in the Valhalla Demo App) breaks the routing:
![bilde](https://github.com/valhalla/valhalla/assets/192418/5e34f9be-9785-4cfd-a8aa-d36e52eaba60)


```json
{
  "costing": "motorcycle",
  "costing_options": {
    "motorcycle": {
      "exclude_polygons": [],
      "maneuver_penalty": 5,
      "country_crossing_penalty": 0,
      "country_crossing_cost": 600,
      "width": 1.6,
      "height": 1.9,
      "use_highways": 0.2,
      "use_tolls": 1,
      "use_ferry": 1,
      "ferry_cost": 300,
      "use_living_streets": 0.5,
      "use_tracks": 0.8,
      "private_access_penalty": 450,
      "ignore_closures": false,
      "ignore_restrictions": false,
      "ignore_access": false,
      "closure_factor": 9,
      "service_penalty": 15,
      "service_factor": 1,
      "exclude_unpaved": 0,
      "shortest": false,
      "exclude_cash_only_tolls": false,
      "top_speed": 140,
      "fixed_speed": 0,
      "toll_booth_penalty": 0,
      "toll_booth_cost": 15,
      "gate_penalty": 300,
      "gate_cost": 30,
      "include_hov2": false,
      "include_hov3": false,
      "include_hot": false,
      "disable_hierarchy_pruning": false,
      "use_trails": 1
    }
  },
  "exclude_polygons": [],
  "locations": [
    {
      "lon": 15.433902740478517,
      "lat": 62.73511203446039,
      "type": "break"
    },
    {
      "lon": 15.354852676391603,
      "lat": 62.68182547122809,
      "type": "via"
    },
    {
      "lon": 15.098090171813967,
      "lat": 62.62366757547452,
      "type": "via"
    },
    {
      "lon": 14.464616775512697,
      "lat": 61.99614966586813,
      "type": "break"
    }
  ],
  "directions_options": {
    "units": "kilometers"
  },
  "id": "valhalla_directions"
}
```

But it's not unique either. If I remove the second via point and replace it with the fourth the routing also breaks.

**Comment by thomthom** [comment]
Btw, the data set I used was fetching `https://download.geofabrik.de/europe-latest.osm.bz2`  on May 10th.

Then I used `osmium extract -p nordics.geojson europe-latest.osm.pbf -o nordics-latest.osm.pbf` to create a smaller data set.

And then the Valhalla docker image to build the graph:
```
docker run --rm --name valhalla_gis-ops -p 8002:8002 -v %cd%/custom_files:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla:latest
```

```
>osmium fileinfo europe-latest.osm.pbf
File:
  Name: europe-latest.osm.pbf
  Format: PBF
  Compression: none
  Size: 30604860537
Header:
  Bounding boxes:
    (-34.49296,29.635548,46.75348,81.47299)
  With history: no
  Options:
    generator=osmium/1.14.0
    osmosis_replication_base_url=http://download.geofabrik.de/europe-updates
    osmosis_replication_sequence_number=4057
    osmosis_replication_timestamp=2024-05-09T20:21:40Z
    pbf_dense_nodes=true
    pbf_optional_feature_0=Sort.Type_then_ID
    sorting=Type_then_ID
    timestamp=2024-05-09T20:21:40Z
```

```
osmium fileinfo nordics-latest.osm.pbf
File:
  Name: nordics-latest.osm.pbf
  Format: PBF
  Compression: none
  Size: 4511998036
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=osmium/1.16.0
    pbf_dense_nodes=true
    pbf_optional_feature_0=Sort.Type_then_ID
    sorting=Type_then_ID
```

**Comment by davidpeck-littlemonkey** [comment]
I've found the same error for some car routes in New Zealand that cross the Cook Strait, If both points are far enough from the coast it gives a `"No path could be found for input"` error:

+ [Auckland to Marlborough (working)](https://valhalla.openstreetmap.de/directions?profile=car&wps=173.935546875%2C-41.516803958101164%2C174.77050781250003%2C-36.86204269508727)
+ [Wellington to Christchurch (working)](https://valhalla.openstreetmap.de/directions?profile=car&wps=172.79296875%2C-43.6281234121246%2C174.869384765625%2C-41.244772343082076)
+ [Auckland to Christchurch (failing)](https://valhalla.openstreetmap.de/directions?profile=car&wps=172.79296875%2C-43.6281234121246%2C174.74853515625003%2C-36.96744946416933)

Failing on both the web examples above and our API server running `ghcr.io/valhalla/valhalla:latest` with tileset [geofabrik: australia-oceania-latest.osm.pbf](https://download.geofabrik.de/australia-oceania-latest.osm.pbf)

**Comment by nilsnolde** [comment]
the requests here seem to work: https://github.com/valhalla/valhalla/issues/4729#issuecomment-2134050207. let us know if this isn't solved yet

**Comment by thomthom** [comment]
> the requests here seem to work: [#4729 (comment)](https://github.com/valhalla/valhalla/issues/4729#issuecomment-2134050207). let us know if this isn't solved yet

I never got it to work. (And because I'm on Windows I didn't have an easy time trying to debug.) Though, I haven't tried recently. It might also very well be that the old pyvalhalla version I used was an issue.
